### PR TITLE
feat(readme): add `youtube_nocookie` as a supported value of `data-vendor`

### PR DESCRIPTION
**Pull request by pan93412**

### CODE REVIEW

**Comment by pan93412** [comment]
assigned to @vb 
thanks! :)

**Comment by pan93412** [comment]
@vb btw can you update npm releases? the current npm releases is too old to support this feature :-)

**Comment by niftylettuce** [comment]
Similar to #34

**Comment by niftylettuce** [comment]
I have emailed @vb for maintainer access on npm/GitHub and also published `@ladjs/lazyframe` in the interim.

**Comment by niftylettuce** [comment]
v2.0.0 released

**Pull request merged**
